<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> - J&J IT Company</title>
    <link rel="stylesheet"href="styles\style.css"/>
    <link
      href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <header>
      <img src="images\b.png" alt="J&J IT Company Logo" />
      <h1>J&J IT Company</h1>
      <nav>
        <ul class="topBotomBordersOut">
          <li><a href="index.php">Home</a></li>
          <li><a href="jobs.php">Job Listings</a></li>
          <li><a href="apply.php">Apply Now</a></li>
          <li><a href="about.php">About Us</a></li>
          <li><a href="enhancement.php">Enhancements</a></li>
        </ul>
      </nav>
    </header>